### ISSUE TITLE
[FEAT] TrackAppendSearchSheet UI Edit

### ISSUE THREAD

**Issue by Junu-Park** [Team-PLAT/Plat-iOS#100]
## 🚩 TO-DO
- [ ] 최근 검색어가 없는 경우, 최근 검색어 부분 제거
- [ ] 검색 중, 최근 검색어 부분 제거
- [ ] 검색 후 검색어 삭제 시, 음악 리스트 로직 수정(X 버튼 -> 음악 리스트 제거 / 지우기 버튼 -> 지울 때 마다 검색)
- [ ] 음악 리스트 상단 패딩 수정
- [ ] 음악 리스트 가장 첫번째 음악 앨범 좌측 상단 모서리 수정
