### ISSUE TITLE
[FEAT] 구독 sheet 해결

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#105]
## 🚩 TO-DO
- [x] 구독 sheet 해결
- [x] 스트리밍 뷰 UI 해결
- [x] trackId 들고 있게 usecase 수정 -> 맵 뷰에서 디테일 뷰 띄워지게
- [x] PlaylistDetailView UI 해결 / 음악 재생 붙이기
- [x] PlaylistDetailView -> 디테일 뷰로 뜨게
- [x] 리스트 뷰 네비게이션
- [ ] user 분리
- [ ] 카야 작업 뷰 api 연결
