### ISSUE TITLE
[FEAT] User 분리

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#121]
## 🚩 TO-DO
- [ ] 유저 아이디 만들어서 분리
- [x]  MusicControlUseCase state 바로 주입 말고 함수 이용
- [ ]  플리 유즈케이스 기기에서 재생 구현
- [ ]  플리 트랙 삭제 구현
- [ ]  플리 수정 뷰 새로운 트랙 생성 구현
- [ ]  플리 뷰 새로운 트랙 생성 구현
- [ ]  맵뷰 핀 앨범 커버로 바꾸깅~ 하하하하
- [ ]  플랫프로세싱풀스크린 애플뮤직 fetch
    - [ ]  스크롤 수정
