### ISSUE TITLE
[FEAT] 플리 뷰 디테일 수정

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#126]
## 🚩 TO-DO 
- [x]  플리 유즈케이스 기기에서 재생 구현
- [x]  플리디테일에딧뷰 트랙 삭제되는 것처럼 구현
- [x]  플리 수정 뷰 **새로운 트랙 생성** 추가
- [x]  플리 뷰 **새로운 트랙 생성** 추가
- [x]  맵뷰 핀 앨범 커버로 바꾸깅~ 하하하하
- [x]  플랫프로세싱풀스크린 애플뮤직 fetch
    - [x]  스크롤 수정
- [ ] ~의 트랙 / 직접 추가됨 나누기
- [ ] 플리 재생 잘 되는지 / 맵 뷰 이미지 테스트 하려무나
