### ISSUE TITLE
[FEAT] AppendPlaylist 기능 구현

### ISSUE THREAD

**Issue by Junu-Park** [Team-PLAT/Plat-iOS#135]
## 🚩 TO-DO
- [ ] 생성 일자 표시 로직 수정
- [ ] 생성 기능 붙이기
- [ ] Playlists View와 연결
- [ ] PlaylistDetail View와 연결
