### ISSUE TITLE
[FEAT] 음악 재생 디테일 해결

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#141]
## 🚩 TO-DO

- [ ] 구독 시트 활성화 비활성화 버튼 체크
- [x] 플리 재생,  플랫팅 뷰 플리 재생  -> 미니 플레이어 뜨게
- [x] 플랫팅 뷰 row 누르면 디테일 뷰 뜨게
- [x] 플랫팅 뷰 api fetch  
- [ ] 모든 플레이리스트 재생 오류
- [ ] 미니 플레이어 다음 곡으로 안넘어감
- [ ] trackUsecase, AppCoordinatorView 수정한 거 지우기
