### ISSUE TITLE
[FIX] TrackAppendSearchSheet 이슈 해결

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#176]
## 🚩 TO-DO
- [x] 트랙게시할때 최근검색어가 순서 맨 뒤로찍힘
- [x] 트랙 추가 시 다시 눌렀을 때 예전 상태 초기화 안됨
- [x] 검색 결과 추가 버튼 너무너무 작아!!!!!!!!! (이미지 문제일 수도)
- [x] 나의 디자인의 꿈을 펼치기
- [ ] 게시할 때 이미지 지그러짐
- [ ] 게시하면 토스트
- [ ] 탈퇴/로그아웃 시에 최근 검색어 삭제
- [ ] 탈퇴 시 신고 유저 디폴트 삭제
