### ISSUE TITLE
[FIX] 플레이리스트뷰 오류 해결

### ISSUE THREAD

**Issue by WooFeather** [Team-PLAT/Plat-iOS#178]
## 🚩 TO-DO
- [ ] 플리 사진 올릴 때 413에러
- [x] 플리 이미지가 있는 상태에서 편집에서 이미지는 그대로인 채 완료할 때 이미지가 기본 이미지로 바뀜
- [x] 플리 사진 이미지 찌그러짐
- [x] 플레이리스트 검색 텍스트필드에서 입력했을 때 x버튼 두개생김
- [ ] 플리뷰에서 어제 만들었던 플리 들어가니까 디코딩에러 -> 음악을 불러오는데 생기는 문제인듯?(isrc->songId)
- [ ] 플리사진 변경 혹은 편집화면 들어갔다가 플레이리스트뷰로 나오니까 앱 죽음 -> PlayListRowView의 onAppear 문제인듯? 음악을 불러오는 문제인듯?(isrc->songId)
