### ISSUE TITLE
[CHORE] 카야 뷰 컨벤션 작업

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#18]
## 🚩 TO-DO
- [x] MARK 주석은 한칸 띄우기
- [x] 로티 스트링 추출
- [x] 후행 클로저 축약 버전 사용하기
- [x] 이미지 = img_이름
- [x] Modifier는 중괄호 아래에 적기
