### ISSUE TITLE
[CHORE] 아서 컨벤션 작업

### ISSUE THREAD

**Issue by Junu-Park** [Team-PLAT/Plat-iOS#20]
## 🚩 TO-DO
- [x] Font extension 추가
- [x] MARK 주석 컨벤션 적용
- [x] 후행 클로저 축약 버전 적용
- [x] Modifier 컨벤션 적용
- [x] 이미지 호출 컨벤션 적용
