### ISSUE TITLE
[FEAT] TrackMapView 추가작업

### ISSUE THREAD

**Issue by WooFeather** [Team-PLAT/Plat-iOS#44]
## 🚩 TO-DO
- [x] 지도에서 각 Track을 탭했을 때 해당 Track의 TrackDetailView로 이동
- [x] 사용자의 실제 위치 가져오기
- [x] LocationManager 파일 따로 관리
- [ ] 주소명 가져오는 부분 처리(서버랑 말해봐야됨)
