### ISSUE TITLE
[FEAT] FeedView 추가 작업

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#54]
## 🚩 TO-DO
- [x] FeedView Usecase
- [x]  재생 중일 때 미니플레이어 띄워야 함 (마지막에 후순위로 붙이면 될 듯)
- [x]  트랙 전체 배열 받아오는 유스케이스 만들기(혹은 처리하기)
- [ ]  api 연결
- [ ]  네트워킹 수행, 음악 재생은 다른 객체,
- [x]  버튼 주석
