### ISSUE TITLE
[FEAT] 애플 뮤직 관련 기능 추가

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#66]
## 🚩 TO-DO
- [x] 구독 시트 
- [x] Apple Music API 음악 정보 Fetch
- [x] TrackFeedView 음악 재생 기능 구현
- [x] MockData 트랙 리스트 연결
- [x] 미니 플레이어 연결
- [x] SeekBar 슬라이더 기능 구현
