### ISSUE TITLE
[FEAT] TrackAppendView 추가 작업

### ISSUE THREAD

**Issue by Junu-Park** [Team-PLAT/Plat-iOS#77]
## 🚩 TO-DO
- [x] 글쓰기 글자 수 제한 기능 구현
- [ ] 최근 검색어 UserDefaults 구현(최대 10개 FIFO 방식)
- [ ] Sheet 자동으로 닫히는 오류 수정
- [x] 글쓰기 단계 Placeholder 추가
- [x] 글쓰기 중 테두리 적용 및 배경 색 변경
- [x] 글쓰기 단계에서 글쓰기만 적용 시, 좌우 Padding 없는 오류 수정
