### ISSUE TITLE
[FEAT] 애플 뮤직 이슈 해결 및 PlaylistDetails뷰 UI 구현

### ISSUE THREAD

**Issue by crownjoe** [Team-PLAT/Plat-iOS#90]
## 🚩 TO-DO
- [x] 구독 여부로 분기 처리
- [x] 첫 빌드는 구독시트 안올라옴 젠장
- [x] 음악 끊기는 이슈 해결
- [ ] PlaylistDetails 뷰 
- [ ] 수정 뷰
- [ ] 음악 재생
- [ ] 임의 재생
- [ ] 삭제
- [ ] 이미지 업로드 어쩌공
