### ISSUE TITLE
[FEAT] TrackAppendContentView Edit

### ISSUE THREAD

**Issue by Junu-Park** [Team-PLAT/Plat-iOS#92]
## 🚩 TO-DO
- [ ] 검색창에서 음악 선택 후 넘어간 화면에서 음악 앨범 화질 저하 현상 수정
- [ ] 글쓰기 화면에서 키보드 올라올 때, 뷰가 툴바와 겹치는 현상 수정
- [ ] 게시하기 기능 구현
- [ ] 피그마와 UI 다른 부분 수정
