### ISSUE TITLE
[FEAT] PlayListDetail 뷰 UI 구현

### ISSUE THREAD

**Issue by Junu-Park** [Team-PLAT/Plat-iOS#97]
## 🚩 TO-DO
- [x] 네비게이션 바(뒤로가기/수정/삭제)
- [x] 사진
- [x] 제목 및 날짜
- [x] 재생 및 임의재생 버튼
- [x] 새로운 트랙 생성 버튼
